version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chin-arm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7wpoukov5qhq"
s3_prefix = "chin-arm"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
