AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Functions for ARM and x86
Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################

  ARMGoFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ArmGoFloat
      CodeUri: ARMGoFloat/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      Timeout: 120
      Tags:
        Name: "ARMGoFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
    Metadata:
      BuildMethod: makefile

  ARMGoFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMGoFloat

  permissionForURLInvokeArmFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMGoFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ARMGoInt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ArmGoInt
      CodeUri: ARMGoInt/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      Timeout: 120
      Tags:
        Name: "ARMGoInt"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
    Metadata:
      BuildMethod: makefile

  ARMGoIntURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMGoInt

  permissionForURLInvokeArmInt:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMGoInt
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ##########################################################################
  #    I N T E L                                                           #
  ##########################################################################

  IntelGoInt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IntelGoInt
      CodeUri: IntelGoInt/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 120
      Tags:
        Name: "IntelGoInt"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
    Metadata:
      BuildMethod: makefile

  IntelGoIntURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref IntelGoInt

  permissionForURLInvokeIntelInt:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelGoInt
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  IntelGoFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IntelGoFloat
      CodeUri: IntelGoFloat/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 120
      Tags:
        Name: "IntelGoFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
    Metadata:
      BuildMethod: makefile

  IntelGoFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref IntelGoFloat

  permissionForURLInvokeIntelFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelGoFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ########################################### MB
  ARMJsFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ArmJsFloat
      CodeUri: JsFloat/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures: [arm64]
      Timeout: 120
      Tags:
        Name: "ARMJsFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute

  ARMJsFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMJsFloat

  permissionForURLInvokeArmJsFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMJsFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ########################################### MB

  IntelJsFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IntelJsFloat
      CodeUri: JsFloat/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 120
      Tags:
        Name: "IntelJsFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute

  IntelJsFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref IntelJsFloat

  permissionForURLInvokeIntelJsFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelJsFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  # JS INT
  IntelJsInt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IntelJsInt
      CodeUri: JsInt/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 120
      Tags:
        Name: "IntelJsInt"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute

  IntelJsIntURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref IntelJsInt

  permissionForURLInvokeIntelJsInt:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelJsInt
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ARMJsInt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ARMJsInt
      CodeUri: JsInt/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - arm64
      Timeout: 120
      Tags:
        Name: "ARMJsInt"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute

  ARMJsIntURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMJsInt

  permissionForURLInvokeARMJsInt:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMJsInt
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

##########################################################################
#   OUTPUTS                                                              #
##########################################################################

Outputs:
  ARMGoFloatLambdafn:
    Value: !Ref ARMGoFloat
    Description: Fn for Go ARM float

  ARMGoFloatLambdaURL:
    Value: !GetAtt ARMGoFloatURL.FunctionUrl

  ARMGoIntLambdafn:
    Value: !Ref ARMGoInt
    Description: Fn for Go ARM Int

  ARMGoIntLambdaURL:
    Value: !GetAtt ARMGoIntURL.FunctionUrl

  ARMJsFloatLambdafn:
    Value: !Ref ARMJsFloat
    Description: Fn for Javascript ARM float

  ARMJsFloatLambdaURL:
    Value: !GetAtt ARMJsFloatURL.FunctionUrl

  ARMJsIntLambdafn:
    Value: !Ref ARMJsInt
    Description: Fn for Javascript ARM Int

  ARMJsIntLambdaURL:
    Value: !GetAtt ARMJsIntURL.FunctionUrl

  IntelGoFloatLambdafn:
    Value: !Ref IntelGoFloatURL
    Description: Fn for Go Intel Float

  IntelGoFloatLambdaURL:
    Value: !GetAtt IntelGoFloatURL.FunctionUrl

  IntelJsFloatLambdafn:
    Value: !Ref IntelJsFloat
    Description: Fn for Javascript Intel float

  IntelJsFloatLambdaURL:
    Value: !GetAtt IntelJsFloatURL.FunctionUrl
