AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Functions for ARM and x86
Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################

  ARMGoFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ArmGoFloat
      CodeUri: ARMGoFloat/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      Timeout: 120
      Tags:
        Name: "ARMGoFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref ARMDynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ARMDynamoDBTable
    Metadata:
      BuildMethod: makefile

  ARMGoFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMGoFloat

  permissionForURLInvokeArmFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMGoFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ARMGoInt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ArmGoInt
      CodeUri: ARMGoInt/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      Timeout: 120
      Tags:
        Name: "ARMGoInt"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref ARMDynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ARMDynamoDBTable
    Metadata:
      BuildMethod: makefile

  ARMGoIntURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMGoInt

  permissionForURLInvokeArmInt:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMGoInt
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ##########################################################################
  #    I N T E L                                                           #
  ##########################################################################

  IntelGoInt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IntelGoInt
      CodeUri: IntelGoInt/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 120
      Tags:
        Name: "IntelGoInt"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref ARMDynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ARMDynamoDBTable
    Metadata:
      BuildMethod: makefile

  IntelGoIntURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref IntelGoInt

  permissionForURLInvokeIntelInt:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelGoInt
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  IntelGoFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IntelGoFloat
      CodeUri: IntelGoFloat/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 120
      Tags:
        Name: "IntelGoFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref ARMDynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ARMDynamoDBTable
    Metadata:
      BuildMethod: makefile

  IntelGoFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref IntelGoFloat

  permissionForURLInvokeIntelFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelGoFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  ########################################### MB
  ARMJsFloat:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ArmJsFloat
      CodeUri: ARMJsFloat/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures: [arm64]
      Timeout: 120
      Tags:
        Name: "ARMJsFloat"
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaExecute

  ARMJsFloatURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ARMJsFloat

  permissionForURLInvokeArmJsFloat:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ARMJsFloat
      FunctionUrlAuthType: "NONE"
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

########################################### MB

##########################################################################
#   OUTPUTS                                                              #
##########################################################################

Outputs:
  ARMDynamo:
    Value: !Ref ARMDynamoDBTable
    Description: DynamoDb Table to test lambdas

  ARMGoFloatLambdafn:
    Value: !Ref ARMGoFloat
    Description: Fn for Go ARM float

  ARMGoFloatLambdaURL:
    Value: !GetAtt ARMGoFloatURL.FunctionUrl

  IntelGoFloatLambdafn:
    Value: !Ref IntelGoFloatURL
    Description: Fn for Go Intel Float

  IntelGoFloatLambdaURL:
    Value: !GetAtt IntelGoFloatURL.FunctionUrl
